version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
